apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: iamroles.iam.amazonaws.com
spec:
  group: iam.amazonaws.com
  names:
    kind: IAMRole
    plural: iamroles
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            description:
              type: string
            inlinePolicy:
              items:
                properties:
                  name:
                    type: string
                  value:
                    type: string
                required:
                - name
                - value
                type: object
              type: array
            maxSessionDuration:
              format: int64
              type: integer
            path:
              type: string
            policies:
              items:
                type: string
              type: array
            trustRelationship:
              type: string
          required:
          - trustRelationship
          type: object
        status:
          properties:
            arn:
              type: string
            roleId:
              type: string
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
