apiVersion: v1
kind: Service
metadata:
  name: {{ template "iam-role-manager.fullname" . }}
  labels:
    control-plane: {{ template "iam-role-manager.fullname" . }}
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    control-plane: {{ template "iam-role-manager.fullname" . }}
    controller-tools.k8s.io: "1.0"
  ports:
  - port: {{ .Values.service.port }}